# Generated by Django 4.1.4 on 2022-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='barre0',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='barre2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
