# Generated by Django 4.1.4 on 2022-12-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_facture_barre0_alter_facture_barre2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='barre0',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='barre1',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='barre2',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='image',
        ),
    ]
