# Generated by Django 4.1.3 on 2022-12-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_bordereauadministratif_remove_facture_prix_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauadministratif',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voir', to='Main.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voir_staff', to='Main.client'),
        ),
    ]
