# Generated by Django 4.1.4 on 2022-12-27 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_facture_barre0_remove_facture_barre1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
