# Generated by Django 4.1.4 on 2022-12-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_facture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordereauadministratif',
            name='admin',
        ),
    ]
