# Generated by Django 4.1.4 on 2023-01-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_facture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
