# Generated by Django 4.1.5 on 2023-07-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0008_alter_client_email_alter_client_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bordereauadministratif",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Main.staffs",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Main.staffs",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Main.staffs",
            ),
        ),
    ]
