# Generated by Django 4.1.5 on 2023-07-23 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0009_bordereauadministratif_staff_client_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bordereauadministratif",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="staff",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
